2025-03-03 16:58:56,096 ERROR: Exception on / [GET] [in /Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/Users/malandru/microblog_2.0/app/routes.py", line 14, in before_request
    if current_user.is_authenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/werkzeug/local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/werkzeug/local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/flask_login/utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/flask_login/utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/flask_login/login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "/Users/malandru/microblog_2.0/app/models.py", line 100, in load_user
    return db.session.get(User, int(id))
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/orm/scoping.py", line 1058, in get
    return self._proxied.get(
           ~~~~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<6 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 3694, in get
    return self._get_impl(
           ~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<7 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 3874, in _get_impl
    return db_load_fn(
        self,
    ...<5 lines>...
        bind_arguments=bind_arguments,
    )
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
    session.execute(
    ~~~~~~~~~~~~~~~^
        q,
        ^^
    ...<2 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/malandru/.pyenv/versions/3.13.1/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-03-03 16:59:41,492 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:00:09,865 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:00:17,349 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:00:58,585 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:01:32,829 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:02:14,266 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:02:25,561 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:03:05,643 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:03:16,101 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:03:23,491 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:03:25,858 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:05:37,457 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:07:56,134 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
2025-03-03 17:09:13,722 INFO: Microblog startup [in /Users/malandru/microblog_2.0/app/__init__.py:59]
